[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://expense-tracker-backend-ym8i.onrender.com/expenseTracker"
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200